const rolePresets = [
  {
    id: "coding",
    targetPersona: "coder",
    name: "Coding达人",
    signature: "代码造万物",
    fellowCount: "1.2 万",
    status: "进行中",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "cyan",
    previewVideo: "videos/超级AI研究所.mp4",
    tags: ["AI编程", "项目复现", "工具链"],
    samples: ["从 0 搭一个 Agent 工具栏", "Cursor 工作流里的 3 个省时动作", "把评论区需求转成可运行 Demo", "AI 编程高手本周必刷清单"]
  },
  {
    id: "exam",
    targetPersona: "coder",
    name: "考研战神",
    signature: "明年此刻，让所有人刮目相看",
    fellowCount: "8632",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "violet",
    previewVideo: "videos/学习.mp4",
    tags: ["考研", "自习室", "复盘"],
    samples: ["23:59 前完成一组错题复盘", "把政治选择题整理成记忆卡", "数学薄弱点今日清零", "上岸作息的一天拆解"]
  },
  {
    id: "reader",
    targetPersona: "reader",
    name: "小说迷",
    signature: "把世界读慢一点",
    fellowCount: "6354",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "amber",
    previewVideo: "videos/小说2.mp4",
    tags: ["阅读", "摘录", "观点"],
    samples: ["一本书只抓一个问题意识", "把短观点沉淀成知识卡", "今天值得慢读的 3 段话", "睡前观点整理"]
  },
  {
    id: "fitness",
    targetPersona: "normal",
    name: "晨练行动派",
    signature: "把精神先叫醒",
    fellowCount: "4821",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "green",
    previewVideo: "videos/今天练练练.mp4",
    tags: ["运动", "早起", "打卡"],
    samples: ["10 分钟唤醒肩颈", "通勤前的轻汗计划", "一周体能打卡表", "低门槛晨练动作组合"]
  },
  {
    id: "foodie",
    targetPersona: "normal",
    name: "治愈料理家",
    signature: "认真吃饭也是自救",
    fellowCount: "1.1 万",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "amber",
    previewVideo: "videos/今天不吃饭.mp4",
    tags: ["美食", "生活", "治愈"],
    samples: ["15 分钟晚餐灵感", "一人食也要好好摆盘", "冰箱剩菜改造", "周末备餐清单"]
  },
  {
    id: "founder",
    targetPersona: "founder",
    name: "产品创业者",
    signature: "从抱怨里找机会",
    fellowCount: "1.7 万",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "pink",
    previewVideo: "videos/实验室研究生.mp4",
    tags: ["产品", "机会", "验证"],
    samples: ["评论区需求如何变成小产品", "一个垂类工具的冷启动路径", "用 AI 做竞品拆解", "本周可验证的 5 个微机会"]
  },
  {
    id: "creator",
    targetPersona: "normal",
    name: "内容实验室",
    signature: "把灵感拍成流量",
    fellowCount: "9400",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "cyan",
    previewVideo: "videos/实验室研究生.mp4",
    tags: ["选题", "脚本", "增长"],
    samples: ["一个选题拆成 5 个短视频角度", "爆款标题的结构复盘", "用 AI 生成脚本初稿", "内容号的一周实验记录"]
  },
  {
    id: "finance",
    targetPersona: "founder",
    name: "理财规划师",
    signature: "把钱花在未来",
    fellowCount: "3290",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "green",
    previewVideo: "videos/基因gogogo.mp4",
    tags: ["理财", "预算", "规划"],
    samples: ["本月支出复盘", "三账户预算法", "消费降噪练习", "一张表看清现金流"]
  },
  {
    id: "language",
    targetPersona: "reader",
    name: "外语沉浸者",
    signature: "每天开口一点点",
    fellowCount: "5176",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "violet",
    previewVideo: "videos/你好我是英语.mp4",
    tags: ["英语", "听力", "口语"],
    samples: ["影子跟读 5 分钟", "今日 20 个场景句", "把短视频改成听力材料", "睡前外语输入清单"]
  },
  {
    id: "other",
    targetPersona: "normal",
    name: "其他（随机视频）",
    signature: "随机抽一个视频看看",
    fellowCount: "更多",
    cooldown: "距下次更换还有27天，或消耗1次人生重置卡立即更换。",
    accent: "cyan",
    disabled: true,
    previewVideo: "videos/实验室研究生.mp4",
    tags: ["随机", "兜底"],
    samples: ["随机视频入口", "暂不支持点击"]
  }
];
